name: SpaceShooter

on: push

env:
  UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}

jobs:
  testAllModes:
    name : space-shooter-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testMode:
          - editmode

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache
      - uses: actions/cache@v2
        with:
          path: SpaceShooter/Library
          key: SpaceShooter/Library

      # Test
      - name: Tests
        uses: webbertakken/unity-test-runner@v2
        with:
          projectPath: SpaceShooter
          unityVersion: 2020.3.3f1
          testeMode: ${{ matrix.testMode }}

      #Ouptput
      - uses: actions/upload-artifact@v1
        with:
          name: Build-Test
          path: artifacts
